version: '3'
services: 
  postgres: 
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "redis:latest"
  nginx:
    depends_on: 
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - "3050:80"
  api:
    depends_on: 
      - postgres
    build:
      dockerfile: Dockerfile.dev # name of the file
      context: ./server # where to look for the file
    volumes: 
      # don't try to veride this folder
      - /app/node_modules
      # whenever app would look inside app (except node_modules) it would get redirected to ./server
      # whenver we make changes in server dir it would be reflected in the app immediately
      - ./server:/app 
    environment: 
      - REDIS_HOST=redis # the name of the service we created here in services:redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres # in services:postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    stdin_open: true
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app # everything in client dir is shared with app dir inside docker
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes: 
      - /app/node_modules
      - ./worker:/app
